version: '3'

services:
  redis:
    image: redis:latest
    container_name: country-info-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - country-info-network

networks:
  country-info-network:
    driver: bridge