import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";
import { Navbar } from "@/components/navbar";
import { QueryProvider } from "./providers/query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Countries info app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-screen`}
      >
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <Navbar />
            <div className="p-10">{children}</div>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
